
services:
  # Orderer service
  orderer.ehr.com:
    image: hyperledger/fabric-orderer
    environment:
      - FABRIC_LOGLEVEL=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_GENERAL_CHAINID=mychannel
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_TLS_ENABLED=true
      - ORDERER_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    volumes:
      - ./crypto-config/ordererOrganizations/ehr.com/orderers/orderer.ehr.com/msp:/var/hyperledger/orderer/msp
      - ./crypto-config/ordererOrganizations/ehr.com/orderers/orderer.ehr.com/tls:/var/hyperledger/orderer/tls
      - ./channel-artifacts:/var/hyperledger/orderer
      - ./crypto-config:/etc/hyperledger/msp
    ports:
      - 7050:7050
    networks:
      - fabric-network

  # Hospital 1 Peer
  peer0.hospital1.ehr.com:
    image: hyperledger/fabric-peer
    environment:
      - CORE_PEER_ID=peer0.hospital1.ehr.com
      - CORE_PEER_ADDRESS=peer0.hospital1.ehr.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.hospital1.ehr.com:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.hospital1.ehr.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.hospital1.ehr.com:7051
      - CORE_PEER_LOCALMSPID=Hospital1MSP
      - CORE_PEER_MSPCONFIGPATH=/var/hyperledger/peer/msp
    volumes:
      - ./crypto-config/peerOrganizations/hospital1.ehr.com/peers/peer0.hospital1.ehr.com/msp:/var/hyperledger/peer/msp
      - ./crypto-config/peerOrganizations/hospital1.ehr.com/peers/peer0.hospital1.ehr.com/tls:/var/hyperledger/peer/tls
      - ./crypto-config:/etc/hyperledger/msp
    ports:
      - 7051:7051
      - 7053:7053
    networks:
      - fabric-network

  # Hospital 2 Peer
  peer0.hospital2.ehr.com:
    image: hyperledger/fabric-peer
    environment:
      - CORE_PEER_ID=peer0.hospital2.ehr.com
      - CORE_PEER_ADDRESS=peer0.hospital2.ehr.com:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer0.hospital2.ehr.com:8052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.hospital2.ehr.com:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.hospital2.ehr.com:8051
      - CORE_PEER_LOCALMSPID=Hospital2MSP
      - CORE_PEER_MSPCONFIGPATH=/var/hyperledger/peer/msp
    volumes:
      - ./crypto-config/peerOrganizations/hospital2.ehr.com/peers/peer0.hospital2.ehr.com/msp:/var/hyperledger/peer/msp
      - ./crypto-config/peerOrganizations/hospital2.ehr.com/peers/peer0.hospital2.ehr.com/tls:/var/hyperledger/peer/tls
      - ./crypto-config:/etc/hyperledger/msp
    ports:
      - 8051:8051
      - 8053:8053
    networks:
      - fabric-network

  # Research Peer
  peer0.research.ehr.com:
    image: hyperledger/fabric-peer
    environment:
      - CORE_PEER_ID=peer0.research.ehr.com
      - CORE_PEER_ADDRESS=peer0.research.ehr.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.research.ehr.com:9052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.research.ehr.com:9051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.research.ehr.com:9051
      - CORE_PEER_LOCALMSPID=ResearchMSP
      - CORE_PEER_MSPCONFIGPATH=/var/hyperledger/peer/msp
    volumes:
      - ./crypto-config/peerOrganizations/research.ehr.com/peers/peer0.research.ehr.com/msp:/var/hyperledger/peer/msp
      - ./crypto-config/peerOrganizations/research.ehr.com/peers/peer0.research.ehr.com/tls:/var/hyperledger/peer/tls
      - ./crypto-config:/etc/hyperledger/msp
    ports:
      - 9051:9051
      - 9053:9053
    networks:
      - fabric-network

networks:
  fabric-network:
    name: fabric-network
